enum EnvNames {
  BASE_URL = "BASE_URL",
  DENO_ENV = "DENO_ENV",
  DB_NAME = "DB_NAME",
  DB_HOST = "DB_HOST",
  DB_USERNAME = "DB_USERNAME",
  DB_PASSWORD = "DB_PASSWORD",
  DB_PORT = "DB_PORT",
  GITHUB_CLIENT_ID = "GITHUB_CLIENT_ID",
  GITHUB_CLIENT_SECRET = "GITHUB_CLIENT_SECRET",
}

export default EnvNames;
